name: food_recipe_demo
description: A demo Flutter project for relaxy

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # my items
  cached_network_image: ^3.2.3
  dio: 4.0.4

  flutter_bloc: 8.0.1
  flutter_svg: 0.22.0
  freezed_annotation: ^2.2.0
  get_it: 7.2.0

  hive: 2.0.4
  hive_flutter: 1.1.0

  json_annotation: ^4.8.1
  intl: 0.17.0
  auto_size_text: 3.0.0

  url_launcher: 6.1.11
  lottie: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # My items
  bloc_test: 9.0.2
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.5
  network_image_mock: ^2.1.1

  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

#  assets:
#    - lib/src/assets/images/
#    - lib/src/assets/icons/