name: Food App CI

#on:
#  push:
#    branches:
#      - *

on: push

jobs:
  flutter_check:
    name: Run flutter basic checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: flutter analyze
        run: flutter analyze